name: SJTTournamentTools
main: Psycle\SJTTournamentTools\SJTTournamentTools
version: 0.0.1
api: 1.11.0

commands:
    addlocation:
        description: "Adds a Location to the configuration"
        usage: "/addlocation <locationname>"
    tptolocation:
        description: "Teleport a player to a location"
        usage: "/tptolocation <playername> <locationname>"

