# The initial spawn point
spawnpoint:
  x: 150
  y: 64
  z: 70

# The list of allowed players
players:
- Player1
- Player2
- Player3
- Player4
- Player5
- Player6
- Player7
- Player8
- Player9
- Player10

# Game types and their configuration
games:
  Parkour:
    duration: 10
    message: Find and touch the Diamond Blocks!
  TreasureHunt:
    duration: 10
    message: Find and touch the Gold Blocks!
  Build:
    duration: 15
    message: Build the best you can!

# Teleport locations
locations:
  Parkour:
    x: 222
    y: 64
    z: 175
  TreasureHunt:
    x: 114
    y: 64
    z: 90
  Build:
    x: 183
    y: 64
    z: 62
  LeisureCentre:
    x: 96
    y: 65
    z: 129
  Gym:
    x: 106
    y: 64
    z: 118
  SportsHall:
    x: 115
    y: 64
    z: 138
  Astro:
    x: 142
    y: 64
    z: 162
  Hall:
    x: 66
    y: 64
    z: 122
  Cafeteria:
    x: 84
    y: 64
    z: 118
  Trees:
    x: 65
    y: 64
    z: 87
  Yard:
    x: 50
    y: 64
    z: 119
  Class1:
    x: 56
    y: 64
    z: 124
  Cupboard:
    x: 56
    y: 64
    z: 133
  Cupboard2:
    x: 49
    y: 64
    z: 133
  Crescent:
    x: 40
    y: 64
    z: 140
  CrescentUpstairs:
    x: 24
    y: 68
    z: 145
  CrescentUostairs2:
    x: 37
    y: 68
    z: 143
  CrescentStairwell:
    x: 24
    y: 68
    z: 149
  PinkRoom:
    x: 27
    y: 65
    z: 171
  CrescentAgain:
    x: 24
    y: 64
    z: 157
  ScienceLobby:
    x: 13
    y: 64
    z: 165
  ScienceUpstairs:
    x: 11
    y: 69
    z: 156
  SEN:
    x: 11
    y: 64
    z: 190
  SENToilets:
    x: 3
    y: 64
    z: 184
  BehindScience:
    x: 1
    y: 64
    z: 170
  Science1:
    x: 5
    y: 64
    z: 164
  ScienceStaffRoom:
    x: 10
    y: 64
    z: 161
  MoreScience:
    x: 7
    y: 65
    z: 151
  MoreScienceUpstairs:
    x: 7
    y: 69
    z: 151
  Sheds:
    x: 5
    y: 64
    z: 130
  Chickens:
    x: 9
    y: 64
    z: 98
  RecreationArea:
    x: 22
    y: 65
    z: 93
  BackSchool:
    x: 45
    y: 64
    z: 49
  Pottery:
    x: 52
    y: 64
    z: 32
  DTYard:
    x: 75
    y: 64
    z: 25
  DT2:
    x: 67
    y: 63
    z: 15
  DT1:
    x: 80
    y: 64
    z: 8
  DT:
    x: 91
    y: 64
    z: 13
  CAD:
    x: 90
    y: 64
    z: 19
  Reception:
    x: 101
    y: 64
    z: 30
  Library:
    x: 77
    y: 64
    z: 44
  SixthForm:
    x: 117
    y: 64
    z: 65
  Entrance:
    x: 123
    y: 64
    z: 25
  BackRoad:
    x: 95
    y: 64
    z: 3

# Scoring
scoreblocks:
  Gold Block: 5
  Diamond Block: 5
