# The initial spawn point
spawnpoint:
  x: 150
  y: 64
  z: 70

# The list of allowed players
players:
- Player1
- Player2
- Player3
- Player4
- Player5
- Player6
- Player7
- Player8
- Player9
- Player10
- Player11

# Game types and their configuration
games:
  Parkour:
    duration: 10
    message: Find and touch the Diamond Blocks!
  TreasureHunt:
    duration: 10
    message: Find and touch the Gold Blocks!
  Build:
    duration: 15
    message: Build the best you can!

# Teleport locations
locations:
  Parkour:
    x: 0
    y: 64
    z: 29
  TreasureHunt:
    x: -109
    y: 64
    z: -56
  Build:
    x: -40
    y: 64
    z: -84
  NewEntrance:
    x: -127
    y: 64
    z: -16
  Gym:
    x: -117
    y: 64
    z: -28
  SportsHall:
    x: -108
    y: 64
    z: -8
  Astro:
    x: -81
    y: 64
    z: 16
  Hall:
    x: -157
    y: 64
    z: -21
  Cafeteria:
    x: -139
    y: 64
    z: -28
  Trees:
    x: -158
    y: 64
    z: -59
  Yard:
    x: -172
    y: 64
    z: -26
  Class1:
    x: -166
    y: 68
    z: -20
  Cupboard:
    x: -166
    y: 64
    z: -11
  Cupboard2:
    x: -174
    y: 64
    z: -11
  Crescent:
    x: -183
    y: 64
    z: -6
  CrescentUpstairs:
    x: -198
    y: 68
    z: 0
  CrescentUpstairs2:
    x: -186
    y: 68
    z: -3
  CrescentStairwell:
    x: -199
    y: 68
    z: 4
  PinkRoom:
    x: -196
    y: 65
    z: 25
  CrescentAgain:
    x: -199
    y: 64
    z: 11
  ScienceLobby:
    x: -211
    y: 64
    z: 21
  ScienceUpstairs:
    x: -210
    y: 69
    z: 12
  SEN:
    x: -212
    y: 64
    z: 44
  BehindScience:
    x: -223
    y: 66
    z: 22
  Science1:
    x: -218
    y: 64
    z: 18
  ScienceStaffRoom:
    x: -213
    y: 64
    z: 15
  MoreScience:
    x: -216
    y: 65
    z: 5
  MoreScienceUpstairs:
    x: -216
    y: 69
    z: 7
  Sheds:
    x: -218
    y: 64
    z: -16
  Chickens:
    x: -214
    y: 64
    z: -48
  RecreationArea:
    x: -201
    y: 65
    z: -53
  BackSchool:
    x: -178
    y: 64
    z: -97
  Pottery:
    x: -171
    y: 64
    z: -114
  DTYard:
    x: -148
    y: 64
    z: -121
  DT2:
    x: -156
    y: 64
    z: -132
  DT1:
    x: -144
    y: 64
    z: -137
  DT:
    x: -132
    y: 64
    z: -133
  CAD:
    x: -133
    y: 64
    z: -127
  OldReception:
    x: -123
    y: 64
    z: -115
  Library:
    x: -145
    y: 64
    z: -100
  SixthForm:
    x: -106
    y: 64
    z: -81
  OldEntrance:
    x: -100
    y: 64
    z: -121
  BackRoad:
    x: -128
    y: 64
    z: -143
